### ISSUE TITLE
Missing functional include in src/chunkmap.h

### ISSUE THREAD

**Issue by Akjosch** [fador/mineserver#182]
src/chunkmap.h uses std::tr1::hash, which is defined in the following include file according to the documentation - http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2005/n1836.pdf page 97:

```C++
#include TR1INCLUDE(functional)
```

The "unordered_map" include often does include "functional" (it uses it for its hasher type argument), but doesn't have to (and in fact it doesn't if you use the Boost variants, like I tried). Consequently, in some configurations leaving this include out will break compiling; adding it after the "unordered_map" include won't hurt though, since all include files have "guards" in them to prevent double inclusion.

**Comment by fador** [comment]
TR1 not used anymore -> closing
