### ISSUE TITLE
User times out, then server crashes

### ISSUE THREAD

**Issue by GTRsdk** [fador/mineserver#215]
[02:38:01] mineserver.cpp:735::run(): Player [PlayerNameHere] timed out
====================== Segmentation Fault ======================
Please note that the Mineserver developers may ask you to re-run this under gdb!
Time of crash: [Oct 28 02:38:01 2012]
Mineserver version: 0.1.17-7a12610
System info: Linux 67-222-146-31 2.6.32-11-pve i686
System version: #1 SMP Wed Apr 11 07:17:05 CEST 2012
C++ Version: 4.6.3
Location: 
BackTrace(0): ./mineserver(_Z13SignalHandleri+0x28) [0x8197fc2]
BackTrace(1): [0xc46500]
BackTrace(2): /lib/i386-linux-gnu/libc.so.6(cfree+0x31) [0x36bb01]
BackTrace(3): /usr/lib/i386-linux-gnu/libstdc++.so.6(_ZdlPv+0x1f) [0xe6026f]
BackTrace(4): ./mineserver(main+0x4a) [0x815c23d]
BackTrace(5): /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xe6) [0x30fe16]
BackTrace(6): ./mineserver() [0x80faeb1]
======================== END OF REPORT ==========================

**Comment by fador** [comment]
I fixed a lot of bugs related to something like this, so closing =)
